<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFrameworks>net10.0-android;net10.0-windows10.0.26100.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ObservApp</RootNamespace>
    <UserSecretsId>350fa6d5-6ac7-4a95-9403-9a763b027e68</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.10" />

    <!-- Syncfusion Blazor -->
    <PackageReference Include="Syncfusion.Blazor.Core" Version="34.1.33" />
    <PackageReference Include="Syncfusion.Blazor.Navigations" Version="34.1.33" />
    <PackageReference Include="Syncfusion.Blazor.Buttons" Version="34.1.33" />
    <PackageReference Include="Syncfusion.Blazor.Inputs" Version="34.1.33" />
    <PackageReference Include="Syncfusion.Blazor.Themes" Version="34.1.33" />
    <!--<PackageReference Include="Syncfusion.Blazor.DropDowns" Version="34.1.32" />
    <PackageReference Include="Syncfusion.Blazor.Grid" Version="34.1.32" />
    <PackageReference Include="Syncfusion.Blazor.Charts" Version="34.1.32" />
    <PackageReference Include="Syncfusion.Blazor.Maps" Version="34.1.32" />
    <PackageReference Include="Syncfusion.Blazor.Notifications" Version="34.1.32" />
    <PackageReference Include="Syncfusion.Blazor.Popups" Version="34.1.32" />
    <PackageReference Include="Syncfusion.Blazor.Spinner" Version="34.1.32" />
    <PackageReference Include="Syncfusion.Blazor.Cards" Version="34.1.32" />
    <PackageReference Include="Syncfusion.Blazor.Calendars" Version="34.1.32" />-->

    <!-- Supabase — nombre correcto desde v1.x -->
    <PackageReference Include="Supabase" Version="1.5.0" />

    <!-- Astronomy Engine — cálculos offline de planetas, luna, eclipses -->
    <PackageReference Include="CosineKitty.AstronomyEngine" Version="2.1.19" />
  </ItemGroup>

</Project>