<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
    <UserSecretsId>feec7888-5523-4348-9efa-8c389fcf7af8</UserSecretsId>
    <!-- Necesario para cambiar la cultura dinámicamente en Blazor WASM -->
    <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.10" />
	<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
	<PackageReference Include="Syncfusion.Licensing" Version="34.2.2" />
  </ItemGroup>

  <PropertyGroup>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebuggerSupport>false</DebuggerSupport>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\ObservApp.Shared\ObservApp.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>