name: Build ObservApp

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Crear appsettings.Local.json
        run: |
          echo '{"SyncfusionLicenseKey": "${{ secrets.SYNCFUSION_LICENSE_KEY }}"}' > ObservApp/appsettings.Local.json

      - name: Restore Android
        run: dotnet restore ObservApp/ObservApp.csproj -p:TargetFramework=net10.0-android

      - name: Restore Windows
        run: dotnet restore ObservApp/ObservApp.csproj -p:TargetFramework=net10.0-windows10.0.26100.0 -p:RuntimeIdentifier=win-x64

      - name: Build Android
        run: dotnet build ObservApp/ObservApp.csproj --framework net10.0-android --configuration Release

      - name: Publish Android
        run: dotnet publish ObservApp/ObservApp.csproj --framework net10.0-android --configuration Release --no-restore --output ObservApp/publish/android

      - name: Build Windows
        run: dotnet build ObservApp/ObservApp.csproj --framework net10.0-windows10.0.26100.0 --configuration Release --no-restore

      - name: Publish Windows
        run: dotnet publish ObservApp/ObservApp.csproj --framework net10.0-windows10.0.26100.0 --configuration Release --no-restore --output ObservApp/publish/windows

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: ObservApp-Android
          path: ObservApp/publish/android/*.apk
          if-no-files-found: warn

      - name: Upload Windows MSIX
        uses: actions/upload-artifact@v4
        with:
          name: ObservApp-Windows
          path: ObservApp/publish/windows/*.msix
          if-no-files-found: warn